#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "------------------- 执行commit-msg校验 -------------------"

# Export Git hook params
export GIT_PARAMS=$*

npx --no-install commitlint --edit "$1"
